# -*- coding: utf-8 -*-
"""ab_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10UlEBOdi8_jA8Z-PiXWsbpbNGOHM-m9W
"""

# ============================================================
# Netflix A/B Testing Lab — Segment 4: Business Decision
# MIS 432 | Carlos Palomares
# ============================================================

# --- Step 1: Import Libraries ---
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency

# --- Step 2: Set a Random Seed ---
np.random.seed(42)

# --- Step 3: Define Experiment Parameters ---
n_users = 1000
prob_a  = 0.24
prob_b  = 0.30

# --- Step 4: Assign Users to Groups ---
groups = np.random.choice(['A', 'B'], size=n_users)

# --- Step 5: Simulate Click Behavior ---
clicks = []
for group in groups:
    if group == 'A':
        click = np.random.binomial(1, prob_a)
    else:
        click = np.random.binomial(1, prob_b)
    clicks.append(click)

# --- Step 6: Build the DataFrame ---
df = pd.DataFrame({
    'user_id': range(1, n_users + 1),
    'group'  : groups,
    'clicked': clicks
})

# --- Step 7: Calculate Summary Metrics ---
summary = df.groupby('group').agg(
    total_users  = ('clicked', 'count'),
    total_clicks = ('clicked', 'sum'),
).reset_index()

summary['ctr'] = summary['total_clicks'] / summary['total_users']

ctr_a = summary.loc[summary['group'] == 'A', 'ctr'].values[0]
ctr_b = summary.loc[summary['group'] == 'B', 'ctr'].values[0]
lift  = ((ctr_b - ctr_a) / ctr_a) * 100

# --- Step 8: Print Results Table ---
print("=" * 45)
print("        Netflix A/B Test — Results Summary")
print("=" * 45)
print(f"{'Group':<10} {'Users':<12} {'Clicks':<12} {'CTR':<10}")
print("-" * 45)
for _, row in summary.iterrows():
    print(f"{'Artwork ' + row['group']:<10} {int(row['total_users']):<12} {int(row['total_clicks']):<12} {row['ctr']:.2%}")
print("=" * 45)
print(f"\n  CTR Artwork A : {ctr_a:.2%}")
print(f"  CTR Artwork B : {ctr_b:.2%}")
print(f"  Lift (B vs A) : +{lift:.1f}%")
print("=" * 45)

# --- Step 9: CTR Bar Chart ---
fig, ax = plt.subplots(figsize=(8, 5))
colors = ['#E50914', '#221F1F']
bars   = ax.bar(
    ['Artwork A (Control)', 'Artwork B (Treatment)'],
    [ctr_a, ctr_b],
    color=colors, width=0.45, edgecolor='white', linewidth=1.2
)
for bar, ctr in zip(bars, [ctr_a, ctr_b]):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.003,
            f'{ctr:.2%}', ha='center', va='bottom',
            fontsize=13, fontweight='bold', color='black')
ax.annotate(f'+{lift:.1f}% Lift',
            xy=(1, ctr_b), xytext=(0.5, (ctr_a + ctr_b) / 2 + 0.02),
            fontsize=11, color='green', fontweight='bold',
            arrowprops=dict(arrowstyle='->', color='green', lw=1.5))
ax.set_ylim(0, max(ctr_a, ctr_b) + 0.08)
ax.set_ylabel('Click-Through Rate (CTR)', fontsize=12)
ax.set_title('Netflix A/B Test — CTR Comparison\nArtwork A vs. Artwork B',
             fontsize=14, fontweight='bold')
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.0%}'))
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(axis='y', linestyle='--', alpha=0.4)
plt.tight_layout()
plt.savefig('ctr_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("  Chart saved as ctr_comparison.png")

# --- Step 10: Statistical Significance Test ---
clicks_a    = int(summary.loc[summary['group'] == 'A', 'total_clicks'].values[0])
clicks_b    = int(summary.loc[summary['group'] == 'B', 'total_clicks'].values[0])
no_clicks_a = int(summary.loc[summary['group'] == 'A', 'total_users'].values[0]) - clicks_a
no_clicks_b = int(summary.loc[summary['group'] == 'B', 'total_users'].values[0]) - clicks_b

contingency_table = [
    [clicks_a, clicks_b],
    [no_clicks_a, no_clicks_b]
]

chi2, p_value, dof, expected = chi2_contingency(contingency_table)
alpha = 0.05

print("\n" + "=" * 45)
print("     Statistical Significance Test Results")
print("=" * 45)
print(f"  Test Used       : Chi-Square Test")
print(f"  Chi-Square Stat : {chi2:.4f}")
print(f"  P-Value         : {p_value:.4f}")
print(f"  Significance    : alpha = {alpha}")
print("-" * 45)
if p_value < alpha:
    print("  RESULT: STATISTICALLY SIGNIFICANT ✅")
    print("  The difference in CTR is likely REAL.")
    print("  → Artwork B is the stronger performer.")
else:
    print("  RESULT: NOT STATISTICALLY SIGNIFICANT ❌")
    print("  The difference may be due to chance.")
print("=" * 45)

# P-Value Chart
fig, ax = plt.subplots(figsize=(8, 4))
bar_colors = ['#2ecc71' if p_value < alpha else '#e74c3c', '#cccccc']
bars = ax.barh(
    ['P-Value', 'Significance\nThreshold (α = 0.05)'],
    [p_value, alpha],
    color=bar_colors, height=0.4, edgecolor='white'
)
for bar, val in zip(bars, [p_value, alpha]):
    ax.text(bar.get_width() + 0.002, bar.get_y() + bar.get_height() / 2,
            f'{val:.4f}', va='center', fontsize=12, fontweight='bold')
ax.set_xlim(0, max(p_value, alpha) + 0.05)
ax.set_xlabel('Value', fontsize=12)
ax.set_title('P-Value vs. Significance Threshold (α = 0.05)',
             fontsize=13, fontweight='bold')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.axvline(x=alpha, color='black', linestyle='--', linewidth=1.2, label='α threshold')
ax.legend(fontsize=10)
plt.tight_layout()
plt.savefig('significance_test.png', dpi=150, bbox_inches='tight')
plt.show()
print("  Chart saved as significance_test.png")

# ============================================================
# SEGMENT 4: Business Decision
# ============================================================

# --- Step 11: Scale the Result to Netflix's Real User Base ---
netflix_users      = 300_000_000      # Netflix's approximate global subscriber count
impressions_per    = 0.10             # Assume 10% of users see this title on a given day
daily_impressions  = netflix_users * impressions_per

# Projected additional clicks per day if Artwork B is deployed
projected_extra_clicks = daily_impressions * (ctr_b - ctr_a)

# --- Step 12: Print the Business Decision Report ---
print("\n" + "=" * 55)
print("         Netflix A/B Test — Business Decision Report")
print("=" * 55)

print("""
EXPERIMENT SUMMARY
------------------
We ran a controlled A/B test exposing 1,000 simulated users
to two versions of artwork for the same Netflix title.
Users were randomly assigned to either the control group
(Artwork A) or the treatment group (Artwork B).
""")

print(f"  Artwork A CTR  : {ctr_a:.2%}  (Control)")
print(f"  Artwork B CTR  : {ctr_b:.2%}  (Treatment)")
print(f"  Lift           : +{lift:.1f}%")
print(f"  P-Value        : {p_value:.4f}")
print(f"  Significant?   : {'YES ✅' if p_value < alpha else 'NO ❌'}")

print("""
STATISTICAL CONCLUSION
----------------------
The Chi-Square test produced a p-value well below the 0.05
threshold, confirming the difference in CTR is statistically
significant. This means the performance gap between the two
artwork versions is real — not a result of random chance.
""")

print("""
BUSINESS RECOMMENDATION
-----------------------
DEPLOY Artwork B as the default artwork for this title
across all users immediately.
""")

print(f"""
PROJECTED BUSINESS IMPACT (at Netflix scale)
--------------------------------------------
  Netflix Subscribers      : {netflix_users:>15,.0f}
  Est. Daily Impressions   : {daily_impressions:>15,.0f}
  CTR Improvement (A → B)  : {(ctr_b - ctr_a):>15.2%}
  Projected Extra Clicks/Day: {projected_extra_clicks:>14,.0f}
""")

print("""
AI FACTORY CONNECTION
---------------------
  Data       → 1,000 simulated user interactions (clicks/no-clicks)
  Model      → Chi-Square statistical comparison of two groups
  Prediction → Artwork B generates a higher CTR than Artwork A
  Decision   → Deploy Artwork B platform-wide
  Value      → Millions of additional content discoveries per day
""")

print("""
PREDICTION-DECISION GAP — CLOSED
---------------------------------
Before the experiment : We predicted B might perform better
After the experiment  : Statistical evidence confirmed it will
The gap is closed     : We can now act with confidence
""")

print("=" * 55)
print("  END OF REPORT")
print("=" * 55)